# Feature extraction

> Chapter on feature extraction or feature learning for image classification. Cover things like CNN, deep learning, fine tuning, etc.

## Things to try:

+ Snapshot ensembling: train a DNN until it converges, increase the learning rate and let it converge again (cyclical learning rates). Each time it converges, save the weigts until the process has been repeated $M$ times. Combine the $M$ networks, each with one of the save $M$ weights to form an ensemble, either by majority vote or weighted averaging.

+ densenet:

    + https://github.com/tdeboissiere/DeepLearningImplementations/blob/master/DenseNet/
    + https://github.com/titu1994/DenseNet
    + https://github.com/liuzhuang13/DenseNet

+ knn feature learning with boundary trees
+ interpretation: http://netdissect.csail.mit.edu/
+ segmentation: https://github.com/msracver/FCIS
+ BN after ReLU

## Outline of Possible approaches

+ maybe different approach for each class

### Segmentation Approach

+ First, I want to model all classes at once and then evaluate the output to see where are the shortcomings.
+ It will most likely be insufficient and therefore I will create separate network for each (subset of) class.
+ Actually, I rather want to first model one class for simplicity and an easier starting point.
+ Let us decide on modelling agriculture first. Might be an ambiguous class, but has the second most examples for non atmosheric labels.
+ Need to decide which pretrained CNN to use for feature extraction.
+ Probably first try VGG for simplicity. See dl course for FCN.

+ I am pretty sure that some of the classes have too few examples to be learned from scratch.
+ For those I will try to determine a way to extract features from a pretrained model and then maybe fit using a simpler model than a DNN.
+ Strongly consider upsampling techniques for these cases.