# Introduction
\label{chp:intro}

## Motivation

The motivation for this thesis is two-fold:

1. Image classification is a highly relevant topic in Computer Vision, Machine Learning and Statistical Learning. It is a thoroughly researched domain and already by many regarded as a 'solved' problem. This progress is mainly attributed to the yearly large-scale image classification competition, *ImageNet*[^imagenet], and the development of *Deep Neural Networks* (DNNs), and more specifically, *Convolutional Neural Networks* (CNNs). The last five winners of ImageNet all used a variant of CNNs in their solution. However, the main focus up until recently was on problems of single label classification. Therefore, the field of multi-label image classification is nowhere near the maturity level of its single-label counterpart. Multi-label classification has a wide range of applications, not only in image classification. It has been applied to problems in text categorisation, multimedia, biology, chemical data analysis, social network mining and e-learning among others. This is most likely the reason why it has seen such a rapid increase of academic publications (see \autoref{pubsperyear}). However, researchers have not yet reached consensus on how to deal with many of the aspects when learning from multi-labelled data, *e.g.* dependency between labels. There are a very limited number of publications specifically dealing with multi-label classification of images, even more so while using DNNs for this task. The field can gain from an up-to-date review of the literature, more statistical perspectives on some of the challenges, additional benchmark datasets and quality empirical evaluations of the theory.  

```{r pubsperyear, include=FALSE, eval = FALSE}
library(tidyverse)
library(ggthemes)
pubsperyear_data <- read_csv("data/Scopus-2251-Analyze-Year.csv")
p <- pubsperyear_data %>% gather(database, No, -YEAR) %>% 
  #mutate(ind2017 = YEAR >= 2017) %>% 
  filter(YEAR < 2017) %>% 
  ggplot(aes(YEAR, No)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Year", y = "# Documents") +
  facet_wrap(~database, labeller = function(variable, value) {
    dnames <- list(Scopus = "(a) Scopus", SemSchol = "(b) Semantic Scholar")
    return(dnames[value])}) 

ggsave("pubsperyear.png", plot = p, device = "png", path = "figures", width = 7, height = 4)
```

![Line graphs illustrating the rise in multi-label learning publications per year for two databases. The database searches were done on 24-03-2017. The searches were not identical since they were limited to the search features of the databases. (a) The search on Scopus (cite) was for all documents (conference papers, articles, conference, articles in press, reviews, book chapters and books) in any subject area with either the words *multi-label* or *multilabel* and either the words *learning* or *classification* found in either their titles, abstracts or keywords. (b) The search on Semantic Scholar was based on machine learning principles and thus automatically decides which research documents are relevant to a specific search query. The query used was *multilabel multi-label learning classification*. The search only returns research in the computer science and neuroscience fields of study. More technical details can be found on the respective engine's websites. \label{pubsperyear}](figures/pubsperyear.png)

2. Deforestation is a massive global problem. It contributes to reduced biodiversity, habitat loss, climate change and other devastating effects. It is said that the world loses an area of forest the size of 48 football fields per minute and the area most affected is in the Amazon basin (cite Kaggle). This problem can be fought more effectively by governments and local stakeholders if better data about the location of deforestation and human invasion on forests are continuously available to them - an ideal task for machine learning! Planet[^planet] and SCCON[^sccon] constructed a dataset of labelled satellite images taken of the Amazon basin and released it as part of a competition on Kaggle[^kaggle], challenging competitors to build algorithms that can automatically label these images with atmospheric conditions and various classes of land use/cover[^usecover]. Resulting algorithms will help the global community better understand where, how, and why deforestation happens all over the world - and ultimately how to respond. A solutions for this task will also contribute to the more broader domain of *Remote Sensing* which could roughly be understood as the analysis of satellite imagery. Again, this domain has many other relevant applications, especially with environmental and infrastructural benefits. For example estimating water and oil reserves, analysing the traffic or determining areas with high poverty, all from just satellite images. (get citations)

[^imagenet]: http://www.image-net.org/
[^planet]: Designer and builder of the world's largest constellation of Earth-imaging satellites - www.planet.com
[^sccon]: Remote sensing experts - www.sccon.com.br/eng
[^kaggle]: Runs programming contests to crowd source machine learning solutions - www.kaggle.com
[^usecover]: Land cover indicates the physical land type such as forest or open water whereas land use documents how people are using the land.

In summary, the relevance in terms of practial and meaningful applications of the topics Multi-Label Classification and Remote Sensing is the main motivation behind this research. Both these research areas are still in their fledgeling phases which also contributes to this choice in research direction. The exact topics to be covered will be given in the next section discussing the aim of the thesis.

## Thesis Objectives

This thesis works towards building a multi-label classifier that can label satellite images of the Amazon as accurately as possible. The method thought best to achieve this goal is to:

1. Identify the most important and latest developments in the literature for: multi-label classification and image classification for remote sensing.
2. Provide an extensive review and discussion of these methods and how they compare to each other.
3. Empirically evaluate and compare them on the satellite image data in order to find the best strategies for our labeling task.

Since practically every state-of-the-art solution to an image classification problem is a CNN, it is reasonable to restrict the space of possible classifiers to CNNs. This thesis should provide the reader with a clear understanding of CNNs and how to effectively apply them to a multi-label classification problem, and especially in the domain of remote sensing. The main contribution of this thesis is a review of multi-label CNNs.

> update this section as progress is made with thesis.

> maybe be more specific

## The Problem

Although the review and evaluation of the literature is the main goal of this thesis, the task of the competition on Kaggle is a secondary objective and what we will use to give our research and discussion direction. Since it is real world example, it will give us a good idea of the needs in practice and thus we can build our research around that. The methods learned to optimise our objective will most likely be transferable to other similar problems.

The task of the competition on Kaggle can be summed up as follows. The competitor is given a training set of satellite images of the Amazon, labelled with various land use and cover labels. The goal is to train a model to learn the relationships between images and labels in order to predict the correct labels for the unlabelled set of satellite images as accurately as possible. This is a typical *supervised learning* task in Statistical Learning and since the output is categorical, this is a *classification* problem. A mathematical definition will be given soon. But first we will investigate the data for this task.

To define the problem more precisely, we follow the conventions of [@Hastie2009]. Let $\boldsymbol{X}\in \mathbb{R}^{p}$ denote a real valued random input vector and $G\in \mathcal{G}$ a categorical variable taking on classes in $\mathcal{G}$. They have a joint distribution $P(\boldsymbol{X},G)$. We seek a function $f(\boldsymbol{X})$ for predicting output $G$ given input $\boldsymbol{X}$. To evaluate the error of the prediction made by $f$ we use a loss function $L(G,f(\boldsymbol{X}))$. Obviously, we want this error made by $f$ to be as small as possible, thus our aim is to minimise the criterion called the expected prediction error:

$$
\mathrm{EPE}=\mathbb{E}\left[L\left(G,f(X)\right)\right]
$$

> not sure how I want to define this and in how much detail?
> give formal definition and explain how it relates to practical problem.
> Introduce f-measure?
> maybe first only cover single label classification

## The Data

This section covers an initial introduction to the data available for the problem at hand. The elements of the data important to know before moving on will be discussed here and the rest will be addressed throughout the thesis, as it becomes relevant to the discussion. This is done here to get a better understanding of the problem before exploring the literature.
